name: passport
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.0 
  firebase_data_connect: ^0.1.2+5
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  provider: ^6.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.0
  photo_manager: ^3.6.3
  mapbox_maps_flutter: ^2.0.0
  flutter_typeahead: ^4.1.1
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/pin.png
    - lib/database/africa.json
    - lib/database/asia.json
    - lib/database/europe.json
    - lib/database/north-america.json
    - lib/database/south-america.json
    - lib/database/oceania.json
    - lib/database/antarctica.json
    - lib/database/central-america.json
